/*(Copyright)

Microsoft Copyright 2015, 2016
Confidential Information

*/
#ifndef _DICE_STATUS_H
#define _DICE_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum DICE_STATUS {
    DICE_SUCCESS = 0,
    DICE_FAILURE = DICE_SUCCESS + 0x80,
    DICE_INVALID_PARAMETER,
    DICE_LOAD_MODULE_FAILED,
    DICE_BAD_FORMAT,
    DICE_INVALID_BOOT_MODE,
    DICE_INVALID_STATE,
    DICE_INVALID_METADATA,
    DICE_INVALID_DEVICE_ID,
    DICE_INVALID_MODULE,
    DICE_INVALID_MODULE_DIGEST,
    DICE_MODULE_UPDATE_FAILED,
    DICE_METADATA_WRITE_FAILED,
    DICE_STATE_UPDATE_FAILED,
    DICE_INVALID_VENDOR_SIGNING_KEY,
    DICE_INVALID_VENDOR_SIGNATURE,
    DICE_INVALID_DEVICE_SIGNATURE,
    DICE_INVALID_TICKET_SIGNATURE,
    DICE_MODULE_UPDATE_NOT_APPROVED,
    DICE_FAILED_UPDATE_POLICY,

    // TODO: THESE ARE GARBAGE
    DICE_FAILURE_METADATA_MISSING,
    DICE_FAILURE_MODULE_LOAD,
    DICE_FAILURE_DEVICE_ID,
    DICE_FAILURE_SKEB_LENGTH,
    DICE_FAILURE_SKEB_DEVICE_SCOPE,
    DICE_FAILURE_SKEB_MODULE_SCOPE,
    DICE_FAILURE_SKEB_CHAINING,
    DICE_FAILURE_SKEB_SIGNATURE,
    DICE_FAILURE_SKEB_STOP_RECORD,
    DICE_FAILURE_VENDOR_SIGNING_KEY,
    DICE_FAILURE_VENDOR_SIGNATURE,
    DICE_FAILURE_DEVICE_SIGNATURE,
    DICE_FAILURE_MODULE_DIGEST,
    DICE_FAILURE_PREV_METADATA_MISSING,
    DICE_FAILURE_PREV_METADATA_INVALID,
    DICE_FAILURE_MODULE_IMAGE_UPDATE,
    DICE_FAILURE_MODULE_UPDATE_NOT_APPROVED,
    DICE_FAILURE_BASIC_UPDATE_POLICY,

    // Argument has an invalid value (e.g. NULL where non-NULL pointer expected)
    DICE_ERROR_INVALID_ARG,
    // Parameter specifies an invalid value for  persistent or dynamic state
    DICE_ERROR_INVALID_STATE,
    // Parameters defining persistent and dynamic state are inconsistent
    DICE_ERROR_ICONSISTENT_STATE,
    // Invalid size (e.g. buffer is too small)
    DICE_ERROR_SIZE,
    // Cryptographic operation failed
    DICE_ERROR_CRYPT
} DICE_STATUS;

#ifdef __cplusplus
}
#endif

#endif
